version: "3.8"
services:
  judgels-server:
    image: ghcr.io/hamgarian/judgels-himalkom/server:latest
    pull_policy: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://${DB_HOST}:3306/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_RABBITMQ_HOST=${RMQ_HOST}
      - SPRING_RABBITMQ_USERNAME=${RMQ_USER}
      - SPRING_RABBITMQ_PASSWORD=${RMQ_PASSWORD}
      - JUDGELS_URLS_CLIENT=${URL_CLIENT}
      - JUDGELS_URLS_API=${URL_API}
      - JUDGELS_URLS_ADMIN=${URL_ADMIN}
    volumes:
      - judgels-data:/var/judgels
    restart: always
  judgels-client:
    image: ghcr.io/hamgarian/judgels-himalkom/client:latest
    pull_policy: always
    environment:
      - API_URL=${URL_API}
    restart: always
  judgels-grader:
    image: ghcr.io/hamgarian/judgels-himalkom/grader:latest
    pull_policy: always
    privileged: true
    environment:
      - SPRING_RABBITMQ_HOST=${RMQ_HOST}
      - SPRING_RABBITMQ_USERNAME=${RMQ_USER}
      - SPRING_RABBITMQ_PASSWORD=${RMQ_PASSWORD}
      - JUDGELS_GRADER_API_URL=${URL_API}
    volumes:
      - grader-data:/var/judgels/grader
      - judgels-data:/var/judgels/server:ro
    restart: always
volumes:
  judgels-data:
  grader-data:
